[package]
name = "fido-authenticator"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/solokeys/fido-authenticator"
documentation = "https://docs.rs/fido-authenticator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delog = "0.1.0"
heapless = "0.7"
rtt-target = "*"
interchange = "0.2.0"
littlefs2 = "0.3"
serde = { version = "1.0", default-features = false }
serde_cbor = { version = "0.11.0", default-features = false }
serde-indexed = "0.1.0"

ctap-types = { git = "https://github.com/solokeys/ctap-types", branch = "main" }

# By defualt pull from github repo. But you can also use local trussed path for
# development. For example:
# trussed = { path = "../../../trussed" }
trussed = { git = "https://github.com/trussed-dev/trussed", branch = "main" }

[features]
enable-fido-pre = []

disable-reset-time-window = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
